version: '3.7'
services:
  apifootball:
    image: apifootball:latest
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - API_KEY=
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HOST=postgres
      - PORT=5432

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'